{{- if .Values.vizaresCE.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vizares.fullname" . }}
  labels:
    {{- include "vizares.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vizaresCE.replicas }}
  strategy:
    {{- toYaml .Values.vizaresCE.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "vizares.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.vizaresCE.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vizares.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.vizaresCE.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vizares.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.vizaresCE.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.vizaresCE.securityContext | nindent 12 }}
          image: "{{ .Values.vizaresCE.image.repository }}:{{ .Values.vizaresCE.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vizaresCE.image.pullPolicy }}
          args:
            - --listen=:8080
            - --data-dir=/data
            {{- if and .Values.vizaresCE.bootstrap.refreshInterval  .Values.existingPrometheus.enabled }}
            - --bootstrap-prometheus-url={{ printf "http://%s.%s:%s" (.Values.existingPrometheus.service.serviceName) (.Values.existingPrometheus.service.serviceNamespace) (.Values.existingPrometheus.service.servicePort | toString ) }}
            - --bootstrap-refresh-interval={{ .Values.vizaresCE.bootstrap.refreshInterval }}
            {{- else if and .Values.vizaresCE.bootstrap.refreshInterval .Values.prometheus.enabled .Values.prometheus.server.enabled }}
            - --bootstrap-prometheus-url={{ printf "http://%s:%s" (include "vizares.prometheus.server.fullname" .) (.Values.prometheus.server.service.servicePort | toString ) }}
            - --bootstrap-refresh-interval={{ .Values.vizaresCE.bootstrap.refreshInterval }}
            {{- end }}
          env:
          {{- if and .Values.clickhouse.enabled }}
            - name: BOOTSTRAP_CLICKHOUSE_ADDRESS
              value: {{ printf "%s:%s" (include "vizares.clickhouse.fullname" .) (.Values.clickhouse.service.ports.tcp | toString ) }}
            {{- if .Values.clickhouse.auth.existingSecret }}
            - name: BOOTSTRAP_CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.auth.existingSecret }}
                  key: {{ .Values.clickhouse.auth.existingSecretKey }}
            {{- else }}
            - name: BOOTSTRAP_CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vizares.clickhouse.fullname" . }}
                  key: "admin-password"
            {{- end }}
            - name: BOOTSTRAP_CLICKHOUSE_USER
              value: {{ .Values.vizaresCE.bootstrap.clickhouse.username }}
            - name: BOOTSTRAP_CLICKHOUSE_DATABASE
              value: {{ .Values.vizaresCE.bootstrap.clickhouse.database }}
          {{- end }}
          {{- with .Values.vizaresCE.env }}
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.vizaresCE.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "vizares.fullname" . }}-data
      {{- with .Values.vizaresCE.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vizaresCE.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vizaresCE.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
