{{- if and .Values.vizaresCE.enabled .Values.vizaresCE.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vizares.serviceAccountName" . }}
  labels:
    {{- include "vizares.labels" . | nindent 4 }}
  {{- with .Values.vizaresCE.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
