{{- if .Values.vizaresCE.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vizares.fullname" . }}
  {{- with .Values.vizaresCE.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "vizares.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vizaresCE.service.type }}
  ports:
    - port: {{ .Values.vizaresCE.service.port }}
      {{- if .Values.vizaresCE.service.nodePort }}
      nodePort: {{ .Values.vizaresCE.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vizares.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: vizares-opentelemetry-collector
  {{- with .Values.vizaresCE.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "vizares.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vizaresCE.service.type }}
  ports:
    - port: 4318
      targetPort: http
      protocol: TCP
      name: otel-http
  selector:
    {{- include "vizares.selectorLabels" . | nindent 4 }}
{{- end -}}
