image:
  repository: gcr.io/ebpf-observability/vizares-node-agent
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
- name: gcr-secret
nameOverride: ""
fullnameOverride: ""
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
podAnnotations: {}

priorityClassName: ""

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

port: 80
scrape: "true"

env: []

collectorEndpoint: ""
apiKey: ""

metricsEndpoint: ""
scrapeInterval: ""

tracesEndpoint: ""
logsEndpoint: ""
profilesEndpoint: ""

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: eks.amazonaws.com/compute-type
  #             operator: NotIn
  #             values:
  #               - fargate