{{- if .Values.podMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "aws-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "aws-agent.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
{{- end -}}
