apiVersion: v2
name: otel-demo
description: otel-demo
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: opentelemetry-demo
    version: 0.28.3
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: vizares
    version: 0.0.2
    repository: https://vizares.github.io/helm-charts
  - name: chaos-mesh
    version: 2.6.3
    repository: https://charts.chaos-mesh.org
